spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project2019down?useUnicodetrue&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  port: 8080

#jackson的配置信息
  spring:
    jackson:
      #日期格式化
      date-format: yyyy-MM-dd HH:mm:ss
      serialization:
        #格式化输出
        indent_output: true
        #忽略无法转换的对象
        fail_on_empty_beans: false
      #设置空如何序列化
      defaultPropertyInclusion: NON_EMPTY
      deserialization:
        #允许对象忽略json中不存在的属性
        fail_on_unknown_properties: false
      parser:
        #允许出现特殊字符和转义符
        allow_unquoted_control_chars: true
        #允许出现单引号
        allow_single_quotes: true

#logback日志配置信息
logging:
  path: D:\javaweb\project2019down\log
  level:
    xatu.zsl: debug
    org.springfromwork: ingo
    org.hibernate: error
#采用相对路径放入
file: log\myspringboot.log
