spring:
    datasource:
        url: jdbc:mysql://localhost:3306/project2019down?useUnicodetrue&characterEncoding=utf-8&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    jpa:
        show-sql: true
server:
    port: 8080

#logback日志配置信息
logging:
    path: D:\javaweb\project2019down\log
    level:
        xatu.zsl: debug
        org.springfromwork: ingo
        org.hibernate: error
#采用相对路径放入
file: log\myspringboot.log
